## server
server:
  port: 8081
## datasource
spring:
  datasource:
    url: jdbc:mysql://byference.com:3306/avancee?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 30000
      connection-test-query: select 1
      pool-name: AdvanceHikariCP
      maximum-pool-size: 15
      minimum-idle: 5
  redis:
    host: localhost
    port: 6379
    password: root
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000
    timeout: 5000
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
  checkExampleEntityClass: true
  safe-delete: true
  safe-update: true